name: safeway  # 프로젝트 이름
description: A pothole detection app  # 프로젝트 설명
version: 1.0.0+1  # 버전 정보

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  permission_handler: ^11.1.0
  geolocator: ^11.0.0
  sensors_plus: ^3.0.2
  http: ^1.1.0
  http_parser: ^4.0.2  # 추가: 멀티파트 요청 처리용
  path_provider: ^2.1.1
  exif: ^3.2.0
  intl: ^0.18.1  # 추가: 날짜 형식 처리용

environment:
  sdk: '^3.7.0'
  flutter: ">=3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/